# Generated by Django 2.0.2 on 2018-05-19 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('reservations', '0001_initial'),
        ('menus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_scale', models.IntegerField(blank=True, null=True)),
                ('feedback_text', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedback', to='reservations.Customer')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_feedback', to='menus.MenuItem')),
            ],
            options={
                'verbose_name_plural': 'Customer Feedback',
            },
        ),
        migrations.CreateModel(
            name='CustomerPayments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_amount', models.FloatField()),
                ('payment_type', models.CharField(max_length=10)),
                ('amount_paid', models.FloatField()),
                ('received_by', models.BigIntegerField()),
                ('receipt_datetime', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='reservations.Customer')),
            ],
            options={
                'verbose_name_plural': 'Customer Payments',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('invoice_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_item_quantity', models.IntegerField()),
                ('menu_item_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Client Invoice Details',
            },
        ),
        migrations.CreateModel(
            name='MasterInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_datetime', models.DateTimeField()),
                ('invoice_amount', models.FloatField()),
                ('invoice_discount', models.FloatField()),
                ('invoice_tax_id', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_invoice', to='reservations.Customer')),
            ],
            options={
                'verbose_name_plural': 'Client Invoice',
            },
        ),
        migrations.CreateModel(
            name='MasterOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('Placed', 'Placed'), ('Pending', 'Pending'), ('Cooking', 'Cooking'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Cooking', max_length=15)),
                ('order_date', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='reservations.Customer')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_order', to='restaurant.MasterDevice')),
                ('order_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_manager', to=settings.AUTH_USER_MODEL)),
                ('premise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premise_order', to='restaurant.MasterPremise')),
                ('served_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='served_by', to=settings.AUTH_USER_MODEL)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_table', to='reservations.MasterTable')),
            ],
            options={
                'verbose_name_plural': 'Master Order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('item_delivery_status', models.CharField(choices=[('Served', 'Served'), ('Ready For Serving', 'ReadyForServing')], max_length=30)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='menus.MenuItem')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oreder_details', to='orders.MasterOrder')),
            ],
            options={
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.AddField(
            model_name='masterinvoice',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_invoice', to='orders.MasterOrder'),
        ),
        migrations.AddField(
            model_name='masterinvoice',
            name='premise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premise_order_invoice', to='restaurant.MasterPremise'),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='orders.MasterInvoice'),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_menuitem', to='menus.MenuItem'),
        ),
        migrations.AddField(
            model_name='customerpayments',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='orders.MasterOrder'),
        ),
        migrations.AddField(
            model_name='customerpayments',
            name='premise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premise_payment', to='restaurant.MasterPremise'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_feedback', to='orders.MasterOrder'),
        ),
    ]
