# Generated by Django 2.0.2 on 2018-05-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_image', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='menus.MenuCategory')),
                ('premise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premise_menu', to='restaurant.MasterPremise')),
            ],
            options={
                'verbose_name_plural': 'Master Category',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_value', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('ref_start_date', models.DateTimeField()),
                ('ref_end_date', models.DateTimeField()),
                ('slug', models.SlugField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='menus.MenuCategory')),
                ('premise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premise_menu_item', to='restaurant.MasterPremise')),
            ],
            options={
                'verbose_name_plural': 'Menu Item',
            },
        ),
    ]
